spring:
  rabbitmq: #RabbitMQ相关的配置
    host: localhost
    port: 5672
    username: guest
    password: guest
eureka:
  client:
    service-url:
      defaultZone: http://admin:admin@localhost:8761/eureka/
