spring:
  rabbitmq: #RabbitMQ相关的配置
    host: 59.110.218.135
    port: 5672
    username: guest
    password: guest
  cloud:
    config:
      profile: dev
      uri: http://8888.b.bangmc.vip/
eureka:
  client:
    service-url:
      defaultZone: http://admin:admin@59.110.218.135:8761/eureka/
  instance:
    hostname: 127.0.0.1
