spring:
  rabbitmq: #RabbitMQ相关的配置
    host: 59.110.218.135
    port: 5672
    username: admin
    password: admin
eureka:
  client:
    service-url:
      defaultZone: http://admin:admin@59.110.218.135:8761/eureka/
