spring:
  rabbitmq: #RabbitMQ相关的配置
    host: 59.110.218.135
    port: 5672
    username: guest
    password: guest
eureka:
  client:
    service-url:
      defaultZone: http://admin:admin@8761.b.bangmc.vip//eureka/
